#!/usr/bin/env bash

source ad2config

case "${Computing_Mode}" in
	"Batch")
		echo "go write the batch bits now."
		exit 1
		Run_Command="${Docking_Batch_Script}  > batch.out 2> batch.err"
		;;
	"Local_Host_Serial")
		Run_Command="run_AD_docking.bash > ad2dock.out 2> ad2dock.err"
		;;
esac

i=1
while [ "${i}" -le "${Number_of_Replicas}" ] ; do
        if [ ! -d "r${i}" ] ; then
                echo "Cannot find docking replica directory. Exiting."
		exit 1
        fi
        cd "r${i}"
	${Run_Command} 
        cd ../
        i=$((i+1))
done



