#!/usr/bin/env bash

source ad2config

# Ensure that a given image is available on the current machine.
# If not, load it from a file.

if [ -z "${AAD2_DOCKER_HOME}" ] ; then
	echo "AAD2_DOCKER_HOME not defined.  Exiting."
	exit 1
fi

source "${AAD2_DOCKER_HOME}/settings.bash"  
# Doing this source gives us the following: AAD2_IMAGE_NAME AAD2_TAG_NAME

# Combine name and tag into convenient string
AAD2_IMAGE_TAG_COMBO="${AAD2_IMAGE_NAME}:${AAD2_TAG_NAME}"
#echo "AAD2_IMAGE_TAG_COMBO=${AAD2_IMAGE_TAG_COMBO}"

# Name of the file for the current image
AAD2_IMAGE_FILE_NAME="${AAD2_IMAGE_FILE_PATH}/${AAD2_IMAGE_TAG_COMBO//:/$'.'}.tar"

COMMAND="bash ${AAD2_DOCKER_HOME}/bin/load_image.bash ${AAD2_IMAGE_TAG_COMBO} ${AAD2_IMAGE_FILE_PATH}"

echo "Using the following command to ensure that the required image is available."
echo ${COMMAND}

LoadAnswer="$(${COMMAND})"
result=$?
if [ "${result}" != "0" ] ; then
	echo "Problem checking for the presence of and/or loading the AAD2 Docker Image."
	echo "Here are the variables used:"
	echo "AAD2_DOCKER_HOME=${AAD2_DOCKER_HOME}"
	echo "AAD2_IMAGE_TAG_COMBO=${AAD2_IMAGE_TAG_COMBO}"
	echo "AAD2_IMAGE_FILE_PATH=${AAD2_IMAGE_FILE_PATH}"
	echo "The return value was ${result}"
	echo "The following was returned on stdout:"
	echo "${LoadAnswer}"
	exit 1
fi

echo "The specified image should be available." 
echo "The load process returned this information:"
echo "${LoadAnswer}"

