#!/usr/bin/env bash

## Validate the contents of the working directory for Automated Antibody Docking

LOGF="ad2_setup.log"

WE_ARE_DONE_WHEN="""
When fully set up, the working directory should contain these things:

    - The antibody PDB file 

    - The glycan PDB file

    - The glycan ring atoms file called 'glycan_ring_atoms.txt'

    - An AD2 configuration file

    - A VC configuration file

    - If Use_Docker is set to True, there should also be a docker config file
"""

UGAGE="""
Usage:

        ${0} [working directory] 

	If the working directory is omitted, the current working directory will be used.

	The script doesn't do much more right now than give directions.
	
	Return:

	    - Indication of success or failure and more info written to a log file.

        Notes:

	    - The two PDB files do not have name restrictions. 
"""

## Set the defaults for config file contents.
Example_AD2_Config="""
MGLToolsPckgs_Location=\"/programs/MGLToolsPckgs\" # works in AD docker
Vina_Carb_Source_Location=\"/programs/src/VC_1_0\" # works in AD docker
Python_2_7_Location=\"/programs/include/python2.7\" # works in AD docker
Antibody_File_Name=\"SomeAntibody.pdb\" # CHANGE ME (unless this is the actual name)
Glycan_File_Name=\"SomeGlycan.pdb\" # CHANGE ME (unless this is the actual name)
Glycan_Flexibility=\"Partial\" # works in AD docker
Number_of_Replicas=\"5\" # works in AD docker
Computing_Mode=\"Local_Host_Serial\" # works from inside AD docker
Use_Docker=\"False\" # works from inside AD docker
Log_File=\"ad2.log\" # the overall log for the N replica(s), their setup and the output analysis
DOCKING_REPLICA_OUTPUT_PDBQT=\"docking_output.pdbqt\" # set the name of the output file from each docking replica
DOCKING_REPLICA_LOG_FILE=\"docking.log\" # set the name of the output from vina-carb for each replica
DOCKING_REPLICA_JOB_LOG=\"ad2_job.log\"  # the log from AAD2 about an individual docking replica
AD2_Docking_Batch_Script=\"\" # if you need to submit docking to a cluster
AD2_Docking_Local_Script=\"\" # if you need to include/source another script in your docking dir
AD2_Setup_Batch_Script=\"\" # if you need to submit setup to a cluster
AD2_Analysis_Batch_Script=\"\" # if you need to submit analysis to a cluster
AD2_Random_Seeds=(
	[1]=\"112345\"
	[2]=\"212345\"
	[3]=\"312345\"
	[4]=\"412345\"
	[5]=\"512345\"
) # Use this if you want deterministic behavior for proving repeatable results.
# Substitute your random number seeds.
# Ensure that the number of entries matches the Number_of_Replicas, above.
"""

Example_Docker_Configuration="""
# Let AAD2 know where the docker utils are.
AAD2_DOCKER_HOME=/path/to/AAD2_Docker
# Configuration file for using AAD2 inside a docker container
# Values initially written into this file are the defaults.
#
# The image name and tag are likely to be out of date. Please check.
Image=\"antibody-docking:2025-02-14-00-54-blf\" # Replace with actual name and tag
#
# The following has essentially no impact on function. 
# If you need a directory path to be named a specific thing, you can make it be that.
# Avoid using system paths (/bin, /usr, /etc and so forth).
# Avoid using anything inside /programs as well.
# Do NOT set it to /home/antibodydocking because you will clobber an internal script that must run.
# If you want to be safe, use something like \"/myAAD2\". The default is also safe.
Internal_Top_Directory=\"/home/antibodydocking/workdir\" # where inside the docker container you want your directory mounted
#
# If you need to run a script before using docker, put its path here.
# Things you might need in such a script:
#    modules to load
#    checks for image presence or loading of images into the local repo
#    setting environment paths, changing user, etc.
# Do not use string \"/path/to/your/script\".
# Note also that the code here can be included in the batch script if submitting to a node.
#    For more on that, see the regular ad2config file.
Pre_Docker_Setup_Script=\"/path/to/your/script\" # replace with the path to your script - this default means 'unset'
"""

Standard_Vina_Carb_Configuration="""
receptor = protein.pdbqt
ligand = ligand.pdbqt
center_x = 0.0
center_y = 0.0
center_z = 11.0
size_x = 32.0
size_y = 32.0
size_z = 36.0
energy_range = 10
num_modes = 20
chi_coeff=1
chi_cutoff=2
"""

if [ -z "${1}" ] ; then
	WORKDIR="$(pwd)"
elif [ ! -d "${1}" ] ; then
        echo "The supplied name must be a directory. Exiting with error."
	echo "The supplied name is: "
	echo "        ${1}  "
        exit 1
else
	WORKDIR="${1}"
fi
echo "Starting the AD2 setup log at: $(date)" > ${LOGF}
echo "Setting the working directory to: ${WORKDIR}" >> ${LOGF}
if [ ! -e "${WORKDIR}/ad2config" ] ; then
        echo "The supplied directory does not contain an ad2config file." >> ${LOGF}
	echo "Writing an example file to the directory." >> ${LOGF}
	echo "${Example_AD2_Config}" > ${WORKDIR}/ad2config.example
	echo "In case you are also using docker, writing an example config for that, too." >> ${LOGF}
	echo "${Example_Docker_Configuration}" > ad2dockerconfig.example
fi
if [ -e "vcconfig" ] ; then
	echo "Found existing vcconfig. Not clobbering it." >> ${LOGF}
else 
	echo "Generating a standard vcconfig." >> ${LOGF}
	echo "${Standard_Vina_Carb_Configuration}" > vcconfig
fi
echo """If you have set random number seeds, they will be put in place later in the process unless you
have already made the subdirectories and placed vcconfig files there. In that case, these scripts will
not overwrite them.
""" >> ${LOGF}
echo """Setup finished.

If there are files ending in .example in this directory, you need to fill the proper values 
into them and remove any values that are not relevant to you. Then, remove '.example' from 
the filenames. Don't forget to add all the needed files to the working directory.
""" >> ${LOGF}

echo "${WE_ARE_DONE_WHEN}" >> ${LOGF}
