#!/usr/bin/env bash
JOB_LOG='job.log'

if [ ! -e "${JOB_LOG}" ] ; then
	echo "The job has not started yet."
	exit 0
fi

if grep -q "Error:" ${JOB_LOG} ; then
	echo "The job completed with an error."
	echo "See the file ${JOB_LOG} for more information."
	exit 0
fi

if grep -q "Job appears to have completed." ${JOB_LOG} ; then
	echo "The job appears to have completed successfully."
	exit 0
fi

if grep -q "Vina-Carb docking job started at" ${JOB_LOG} ; then
	echo "The job has started." 
	exit 0
fi

