#!/usr/bin/env bash
declare -A AD2_Random_Seeds
source ad2config
if [ -z "${Number_of_Replicas}" ] ; then
	echo "Number of replicas not specified. Exiting"
	exit 1
fi
if [ -z "${Log_File}" ] ; then
	Log_File="ad2.log"
fi

## set up directories for each replica to be run
i="1"
while [ "${i}" -le "${Number_of_Replicas}" ] ; do
	if [ ! -d "r${i}" ] ; then
		mkdir "r${i}"
	else
		echo "INFO: Found preexisting directory for replica ${i}. Not clobbering."  >> ${Log_File}
	fi
	## set symbolic links inside the directories
	cd "r${i}" 
	echo "INFO: AD2 log of docking replica run started on $(date)" > ${Log_File}
	if [ ! -e "vcconfig" ] ; then
		cp ../vcconfig .
		if [ -z "${AD2_Random_Seeds[${i}]}" ] ; then
			echo "INFO: Using default vcconfig for replica ${i}."  >> ${Log_File}
		else
			echo "INFO: Setting random seed for replica ${i} to ${AD2_Random_Seeds[${i}]}" >> ${Log_File}
			echo "seed=${AD2_Random_Seeds[${i}]}" >> vcconfig
		fi
		if [ -z "${AD2_Docking_CPUS}" ] ; 
			echo "INFO: Using default number of CPUs=8 and setting exhautiveness to match." >> ${Log_File}
			echo "cpu=8" >> vcconfig
			echo "exhaustiveness=8" >> vcconfig
		else
			echo "INFO: Using ${AD2_Docking_CPUS} CPUs and setting exhautiveness to match." >> ${Log_File}
			echo "cpu=${AD2_Docking_CPUS}" >> vcconfig
			echo "exhaustiveness=${AD2_Docking_CPUS}" >> vcconfig
		fi
	
	else
		echo "INFO: Found preexisting vcconfig for replica ${i}. Not clobbering." >> ${Log_File}
	fi
	if [ ! -e "ad2config" ] ; then
		cp ../ad2config .
	else
		echo "INFO: Found preexisting ad2config for replica ${i}. Not clobbering." >> ${Log_File}
	fi
	if [ ! -e "protein.pdbqt" ] ; then
		cp ../protein.pdbqt .
	else
		echo "INFO: Found preexisting protein.pdbqt for replica ${i}. Not clobbering." >> ${Log_File}
	fi
	if [ ! -e "ligand.pdbqt" ] ; then
		cp ../ligand.pdbqt .
	else
		echo "INFO: Found preexisting ligand.pdbqt for replica ${i}. Not clobbering." >> ${Log_File}
	fi
	#  copy the submission script if in batch mode. 
	if [ ! -z "${AD2_Docking_Batch_Script}" ] ; then
		if [ ! -e "${AD2_Docking_Batch_Script}" ] ; then
			echo "ERROR: AD2_Docking_Batch_Script specified but not found. Exiting." >> ${Log_File}
			echo "       The name given is: ${AD2_Docking_Batch_Script}" >> ${Log_File}
			exit 1
		fi
		echo "INFO: copying the indicated script for batch processing." >> ${Log_File}
		cp ../${AD2_Docking_Batch_Script} .
	fi
	#  copy the submission config if in batch mode. 
	if [ ! -z "${AD2_Docking_Local_Script}" ] ; then
		if [ ! -e "${AD2_Docking_Local_Script}" ] ; then
			echo "ERROR: AD2_Docking_Local_Script specified but not found. Exiting." >> ${Log_File}
			echo "       The name given is: ${AD2_Docking_Local_Script}" >> ${Log_File}
			exit 1
		fi
		echo "INFO: copying the local config script for batch processing." >> ${Log_File}
		cp ../${AD2_Docking_Local_Script} .
	fi
        cd ../
	i=$((i+1))
done

