#!/usr/bin/env bash

## 
## run_test.bash for the cluster utilities in AAD2
## 

if [ ! -e "Local_Settings.bash" ] ; then
    echo "You need to make a file called Local_Settings.bash in this directory."
    echo "The current directory is:"
    echo "$(pwd)"
    echo "Please see the Readme.md in this directory for more info."
    exit 1
fi

source Local_Settings.bash

if [ -z "${AAD2_IMAGE_FILE_PATH}" ] ; then
    echo "AAD2_IMAGE_FILE_PATH undefined.  Exiting."
    exit 1
fi
if [ -z "${AAD2_DOCKER_HOME}" ] ; then
    echo "AAD2_DOCKER_HOME undefined.  Exiting."
    exit 1
fi
if [ -z "${AAD2_CLI_BIN_PATH}" ] ; then
    echo "AAD2_CLI_BIN_PATH undefined.  Exiting."
    exit 1
fi
if [ -z "${Image}" ] ; then
    source ${AAD2_DOCKER_HOME}/settings.bash
    if [ -z "${AAD2_IMAGE_NAME}" ] || [ -z "${AAD2_TAG_NAME}" ] ; then
        echo "Image undefined and cannot get info from AAD2_Docker's settings.sh.  Exiting."
        exit 1
    else
        Image="${AAD2_IMAGE_NAME}:${AAD2_TAG_NAME}" 
    fi
fi


AD2CONFIG="""#!/usr/bin/env bash

## ad2config autogenerated by the testing script

Log_File=\"ad2.log\" 
DOCKING_REPLICA_LOG_FILE=\"docking.log\" 
DOCKING_REPLICA_JOB_LOG=\"ad2_job.log\"  

Antibody_File_Name=\"UPLOADED_2H1_PDB_MONOMER_.pdb\"
Glycan_File_Name=\"DManpa1-8DNeup5Acb2-4DFrufa2-OH_structure.pdb\"
Glycan_Flexibility=\"Partial\"
Number_of_Replicas=\"5\"
Computing_Mode=\"Batch\"
AD2_Random_Seeds=(
        [1]=\"1770199568\"
        [2]=\"-342100090\"
        [3]=\"1840569422\"
        [4]=\"-271726951\"
        [5]=\"1910945648\"
)
AD2_Docking_CPUS=\"28\" 
AD2_Exhaustiveness=\"56\" 
Use_Docker=\"True\" 
AD2_Docking_Batch_Script=\"submit_docking_to_slurm_with_docker.bash\"
AD2_Docking_Local_Script=\"gwconfig\"

AAD2_IMAGE_FILE_PATH=\"${AAD2_IMAGE_FILE_PATH}\"
Image=\"${Image}\"
AAD2_DOCKER_HOME=\"${AAD2_DOCKER_HOME}\"
AAD2_CLI_BIN_PATH=\"${AAD2_CLI_BIN_PATH}\"

Use_VMD=\"${Use_VMD}\"
VMD_HOME=\"${VMD_HOME}\" # Path to the 'vmd' binary, e.g., /programs/bin
VMD_LIB=\"${VMD_LIB}\" # Path to the 'vmd' lib directory, e.g., /programs/lib

"""

cp -r inputs.all-five outputs

echo "${AD2CONFIG}" > outputs/ad2config

export PATH=${AAD2_CLI_BIN_PATH}:$PATH

echo "PATH is $PATH"
#exit

( cd outputs && run_cluster_AAD2_from_CLI.bash )
