#!/usr/bin/env bash

# Submits jobs to a cluster's queuing system (or other spawned location) and monitors their output.
# When the jobs are complete, it calls AD_Analyze on the results.

# Should be called from the top directory - the one above the 'rN' directories.

source ad2config

if [ -z "${Log_File}" ] ; then
	Log_File='ad2.log'
fi

if [ "${Computing_Mode}" != "Batch" ] ; then
	echo "FATAL: Script requires Computing_Mode to be Batch. Exiting." >> ${Log_File} 2>&1
	echo "       Name of script called: ${0}" >> ${Log_File} 2>&1 
	exit 1
fi

if [ -z "${AD2_Docking_Batch_Script}" ] ; then
	echo "FATAL: Computing_Mode is set to Batch but no submission script defined. Exiting." >> ${Log_File} 2>&1 
	exit 1
fi


prepare_AD_docking_directory  # this should be on the PATH

N="1"
errors="False"
while [ "${N}" -le "${Number_of_Replicas}" ] ; do
        echo "submitting number ${N}"
	( cd "${WD}/r${N}" && bash ${AD2_Docking_Batch_Script} )
	the_returnval="$?"
	if [ "${the_returnval}" != "0" ] ; then
		echo "ERROR: Non-zero return value from submission of job r${N}" >> ${Log_File} 2>&1 
		errors="True"
	fi
        N="$((N+1))"
done

if [ "${errors}" == "True" ] ; then
	echo "WARNING: Submission returned errors. Proceeding to Monitor anyway." >> ${Log_File} 2>&1
	echo "         Check the monitoring log for details.." >> ${Log_File} 2>&1
else
	echo "INFO: Submission completed without errors." >> ${Log_File} 2>&1
fi

nohup monitor_and_analyze  > monitor_and_analyze_stderr_stdout.log 2>&1  &


#if [ "${errors}" == "True" ] ; then exit 1 fi
