GLYLIB = /programs/src/AD2_GLYLIB/lib
GLYINC = /programs/src/AD2_GLYLIB/inc
FLAGS = -I$(GLYINC) -L$(GLYLIB) -lglylib -Wall -lm -fcommon
SOURCE = get_flexible_bond_info.c
OUTEXE = get_flexible_bond_info


default:
	 gcc $(SOURCE) $(FLAGS) -g -o $(OUTEXE)


